name: MomoCommand
main: moe.kouyou.momocommand.MomoCommand
version: 1.0.0
author: kouyoux
description: a powerful custom command plugin

# commands:
#   momocommand:
#     aliases:
#       - mcmd

# permissions:
#   momocommand.admin:
#     default: op
